# Generated by Django 4.2.5 on 2023-09-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeFunctionsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=60, unique=True)),
                ('function_name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=255)),
                ('short_code', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fake Functions Data',
                'db_table': 'functions_data',
            },
        ),
    ]
